#%RAML 0.8
---
title: Comet Server Microservices
version: v1

/authentication:
  /users:
    get:
      description: test description
      responses:
        200:
          description: OK
          body:
            application/json:
              example:
    post:
    put:

/projects:
  get:
  post:
  put:

/channels:
  get:
  post:
  put:
